EvalConf:
  multi_object: false
  max_steps: 2500
  max_dist: 1.0
  is_gibson: False
  dataset_type: "mp3d"
  object_nav_path: "datasets/objectnav_mp3d_v1/val_mini/content/"
  scene_path: "datasets/scene_datasets/"
  log_rerun: False
  use_pointnav: False
  square_im: True
  results_path: "results/mp3d_argmax_c25"
  ep_end: 999999

config: [
  ./controller_habitat.yaml,
  ./mapping_gclip_argmax_c25.yaml,
  ./planning_conf.yaml
]
