EvalConf:
  multi_object: false
  max_steps: 1000
  max_dist: 1.0
  is_gibson: False
  object_nav_path: "datasets/objectnav_hm3d_v1/val_mini/content/"
  scene_path: "datasets/scene_datasets/"
  log_rerun: False
  use_pointnav: False
  square_im: True
  results_path: "results/minival_ov_yolocp_ov_s2/"
  ep_start: 20
  ep_end: 30

config: [
  ./controller_habitat.yaml,
  ./mapping_conf_sim_yolocp.yaml,
  ./planning_conf_ov.yaml
]
