EvalConf:
  multi_object: false
  max_steps: 2500
  max_dist: 1.0
  is_gibson: False
  dataset_type: "mp3d"
  object_nav_path: "datasets/objectnav_mp3d_v1/val_mini/content/"
  scene_path: "datasets/scene_datasets/"
  log_rerun: False
  use_pointnav: False
  square_im: True
  results_path: "results/mp3d_wgate_mp3d_v5e_full_mini"
  ep_end: 999999
  include_ids: [2, 8, 13, 16, 26, 31]

config: [
  ./controller_habitat.yaml,
  ./mapping_conf_sim_gclip_oacp_wgate_mp3d_v5e.yaml,
  ./planning_conf.yaml
]
