PlanningConf:
  percentile_exploitation: 99.0
  frontier_depth: 2.5
  no_nav_radius: 0.9
  yolo_confidence: 0.8
  filter_detections_depth: False
  consensus_filtering: True
  allow_replan: True
  use_frontiers: True
  allow_far_plan: False
  using_ov: False
  max_detect_distance: 0.5
  obstcl_kernel_size: 0.5
  min_goal_dist: 0.7
